name: 'Deploy AWS Resources'

on:
  workflow_run:
    workflows: ["Python Lambda Tests"]  # The name of the test workflow
    types: [completed]
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  TF_VAR_image_uri: ${{ secrets.PREDICTIONS_LAMBDA_IMAGE_URI }}

jobs:  
  Docker-Build-Push:   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    - name: Docker Login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
    
    - name: Build and Push Docker Images
      run: |
        export ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
        bash scripts/create_pkg.sh

  terraform:
    needs: Docker-Build-Push
    name: "Terraform infrastructure change management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repository to Runner
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.3.0
      
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: format
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terrafrom Apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan