name: 'Deploy AWS Resources'

on:
  workflow_run:
    workflows: ["Zip and Upload Lambda Functions"]  # The name of the test workflow
    types: [completed]
  pull_request:
    branches:
      - main
env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
jobs:  
  To-Zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Zip
      run: sudo apt-get install 
    
    - name: Directory details
      run: ls -a
    
    - name: Create Dependency Package
      run: bash scripts/create_pkg.sh

    - name: Upload Lambda Functions to S3
      run: |
        for dir in /lambda; do
          if [ -d "$dir" ]; then
            aws s3 cp "${dir}.zip" "s3://stock-market-site/lambda/${dir}.zip"
          fi
        done
    - name: Upload Lambda Artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: lambda-zips
        path: lambda/*.zip

  terraform:
    needs: To-Zip
    name: "Terraform infrastructure change management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout the repositoryy to the runner
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.3.0

      - name: Download Lambda
        uses: actions/download-artifact@v4
        with:
          name: lambda-zips
          path: terraform/lambda/
      
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform format
        id: format
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false
        continue-on-error: true
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terrafrom Apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan